FROM python:3.8-slim-buster
ENV PYTHONUNBUFFERED=1
WORKDIR /django
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# nano /usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py